version: '3.9'
services:
  db:
    image: postgres
    restart: always
    user: root
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    ports:
      - "5432:5432"